title: Penambangan Data
author: Cucu Hasanatul Ahfa
logo: image.png

execute:
  execute_notebooks: off

repository:
  url: https://github.com/cucuhasanatulahfa/Pendataa
  branch: main

html:
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_toc: true
  navbar_footer_text: "© 2026 Cucu Hasanatul Ahfa"